### ISSUE TITLE
How to disable fcitx5 autostart while start nvim?

### ISSUE THREAD

**Issue by laowalter** [pysan3/fcitx5.nvim#1]
The plugins is pretty good, thank you. Well, I am not always run fcitx5, but with this plugin fcitx5 will auto start when I open nvim. I would like to work in pure English environment until I  manually run fcitx5.

**Comment by pysan3** [comment]
Hi @laowalter, thanks for using this plugin!

Would you mind sharing what package manager you are using?
It should be pretty easy to achieve that by using some of the options of your plugin manager.

If you are using `lazy.nvim`, you can set something like this. This plugin will only be loaded when any of the `cmd` are called.

```lua
{
  "pysan3/fcitx5.nvim",
  cmd = {
    "Fcitx5",
    "Fcitx5SetName",
    "Fcitx5Geneious",
    "Fcitx5OnModeChanged",
    "Fcitx5SetPrior",
    "Fcitx5GetImname",
    "Fcitx5GetImnames",
  },
  opts = {
    -- ... Your Config
  },
}
```

If you use other package managers, please tell me which one and I think I can help you out.

**Comment by pysan3** [comment]
Or, did you mean that you want the plugin to check whether `fcitx5-remote` command (`[no option]`) outputs `0` (i.e. fcitx5 is closed), and do not call `fcitx5-remote` to keep it closed?

```txt
Usage: fcitx5-remote [OPTION]
	-c		inactivate input method
	-o		activate input method
	-r		reload fcitx config
	-t,-T		switch Active/Inactive
	-e		Ask fcitx to exit
	-a		print fcitx's dbus address
	-m <imname>	print corresponding addon name for im
	-g <group>	set current input method group
	-q		Get current input method group name
	-n		Get current input method name
	-s <imname>	switch to the input method uniquely identified by <imname>
	[no option]	display fcitx state, 0 for close, 1 for inactive, 2 for active
	-h		display this help and exit
```

**Comment by pysan3** [comment]
> did you mean that you want the plugin to check whether fcitx5-remote command ([no option]) outputs 0 (i.e. fcitx5 is closed), and do not call fcitx5-remote to keep it closed?

In my environment, when I run `fcitx5-remote` with fcitx5 closed, it returns `0` but starts fcitx5 at that moment.

Does this happen on your PC as well @laowalter? If yes, maybe there's no real way to even check whether fcitx5 is running (via shell commands) without starting the program so this might not be possible.

Do you know any way to get around this behavior?

**Comment by laowalter** [comment]
Thanks for your reply.

1. The fcitx5-remote return 0 when fcitx5 killed in my environment too. this could check if fcitx5 is running.
2. I use Astronvim, an integrated nvim, and custom my config in ~/.config/nvim/lua/user
3. Astronivm uses lazy as the plugin manager.

Here is my custom config in Astronivm located in ~/.config/nvim/lua/user/plugins/fcitx5.lua:
```
return {
  "pysan3/fcitx5.nvim",
  cond = vim.fn.executable "fcitx5-remote" == 1,
  event = { "ModeChanged" },

  config = function()
    local en = "keyboard-us"
    local cn = "pinyin"
    require("fcitx5").setup {
      imname = {
        norm = en,
        ins = en,
        cmd = en,
      },
      remember_prior = false,
    }
  end,
}
```

it works good, when I start vim, fcitx5 will automatically start. In new config I tried add the `cmd part`  you provide in that position, when I start nvim, fcitx5 still started automatically, furthermore, hot key `ctrl+space` can not active the input state. I am not use lua and not familiar  with lazy as well. Maybe my config is wrong.
Here is the new config:

```
return {
  "pysan3/fcitx5.nvim",
  cmd = {
    "Fcitx5",
    "Fcitx5SetName",
    "Fcitx5Geneious",
    "Fcitx5OnModeChanged",
    "Fcitx5SetPrior",
    "Fcitx5GetImname",
    "Fcitx5GetImnames",
  },
  cond = vim.fn.executable "fcitx5-remote" == 1,
  event = { "ModeChanged" },

  config = function()
    local en = "keyboard-us"
    local cn = "pinyin"
    require("fcitx5").setup {
      imname = {
        norm = en,
        ins = en,
        cmd = en,
      },
      remember_prior = false,
    }
  end,
}
```

**Comment by pysan3** [comment]
Quick response, please delete the `event = ` line in the config. 

This will not load fcitz5.nvim altogether until you explicitly run any of the `cmd` and therefore fcitz5 will not autostart. 

This should be good for a temporary solution but I'll add some code to check whether fcitz5 is running or not *inside* the plugin as well for better ux later. Plz wait till this weekend or so.

**Comment by laowalter** [comment]
> Quick response, please delete the `event = ` line in the config.

Great! As you mentioned, commenting out the line event= is a temporary solution that will prevent fcitx5 from starting automatically. However, there is an  another problem. After I manually start fcitx5, I need to exit the terminal (kitty) and open a new one before fcitx5 input can be activated in nvim, just reopen nvim in the current terminal can not activate fcitx5.

Thanks for you quick reply. I am appreciated.

**Comment by pysan3** [comment]
Thanks for confirming. 

I will try to add code to auto detect whether fcitz5 is running later but in the meantime, please run any of the commands to start this plugin after you manually start fcitz5. 

I believe `:Fcitz5SetPrior` would be the best one in this case. 

> After I manually start fcitx5, I need to exit the terminal (kitty) and open a new one before fcitx5 input can be activated

Not being able to type with fcitz5 inside kitty should be an issue of fcitz5/kitty/neovim and don't think it's a problem with this plugin. 

Does it work if you instead type on bash command line? Or how about a different terminal app?

**Comment by laowalter** [comment]
I just found that, if i remove `event=` line, in vim when i switch from insert mode to normal mode, the ime state did not work as I expect that only English available on normal mode. so I have to add the line again.

**Comment by pysan3** [comment]
> I just @do we s@[]() (lazy loaded) alt  ~~e~~e~~~~dads~~~~~~~~by ogether. And in order to use the plugin, you have to manually start the plugin by `require("fcitz5")` ~~~~or by calling one of the commands. 

De see try

Your solution here is not correct. 
> ~~~~IMO try wek~~~~r~~~~

**Comment by laowalter** [comment]
Understood. Since I really do not be good at lua and vim programming , although have used to  vim from decades, just let it be. 

Thanks for your help.

**Comment by pysan3** [comment]
Sorry mate, it seems like I was so sleepy and I sent a very cryptic nonsense lol.

 > the ime state did not work as I expect that only English available on normal mode
 
 In order to not autostart fcitz5, the plugin is disabled altogether now when you delete `event = ` line. So, even when fcitz5 is active when starting neovim, you have to always manually invoke this plugin by either `require("fcitz5")` or by running any of the commands.

I'd say running `:Fcitz5SetPrior` would be the best for your situation to invoke this plugin.

Later on, I will add a feature so that we don't need to go through all this hassle.

**Comment by pysan3** [comment]
So after all the hassle, I've implemented a detecting mechanism so that you don't need to worry about much.

Please forget about all the conversations and go back to your old config (with `event =` line and all others).

Instead, add this option and set to `false` to disable autostarting fcitx5 on startup as explained in https://github.com/pysan3/fcitx5.nvim#setup.

```lua
  autostart_fcitx5 = true, -- boolean: if true, autostarts `fcitx5` when it is not running.
```

**Comment by laowalter** [comment]
Thanks you!, GREAT!  Tested, works well.

**Comment by pysan3** [comment]
Thanks for testing @laowalter :D
